import { StyleSheet, Dimensions } from 'react-native';
import { s, vs, ms } from '../../../Utility/Scaling';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const createStyles = colors =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingHorizontal: s(10),
      paddingBottom: vs(120),
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: vs(10),
      paddingHorizontal: s(10),
    },
    headerIcons: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(5),
    },
    vpBadge: {
      backgroundColor: colors.warningAlpha,
      borderColor: colors.warning,
      borderWidth: 1,
      paddingHorizontal: s(10),
      paddingVertical: vs(5),
      borderRadius: ms(20),
    },
    streakBadge: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderWidth: 1,
      paddingHorizontal: s(10),
      paddingVertical: vs(5),
      borderRadius: ms(20),
    },
    notificationBell: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderWidth: 1,
      padding: s(8),
      borderRadius: ms(20),
      position: 'relative',
    },
    notificationDot: {
      position: 'absolute',
      top: -2,
      right: -2,
      backgroundColor: colors.error,
      minWidth: s(14),
      height: s(14),
      borderRadius: s(7),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.background,
    },
    vehicleCard: {
      backgroundColor: colors.cardDark,
      borderRadius: ms(24),
      paddingHorizontal: s(16),
      paddingVertical: vs(5),
      borderWidth: 1,
      borderColor: colors.borderTranslucent,
      alignItems: 'center',
      marginBottom: vs(12),
      overflow: 'hidden',
      position: 'relative',
    },
    skinsLabel: {
      position: 'absolute',
      top: vs(12),
      right: s(12),
      backgroundColor: colors.overlayLight,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 6,
      paddingHorizontal: s(8),
      paddingVertical: vs(3),
      zIndex: 10,
    },
    carEmoji: {
      marginTop: vs(-5),
      textShadowRadius: 20,
      textShadowColor: 'rgba(255,255,255,0.1)',
    },
    rankContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      alignItems: 'flex-end',
      marginBottom: vs(8),
    },
    rankStats: {
      alignItems: 'flex-end',
    },
    progressBarContainer: {
      width: '100%',
      height: vs(6),
      backgroundColor: colors.border,
      borderRadius: vs(3),
      marginBottom: vs(8),
    },
    progressBar: {
      height: '100%',
      backgroundColor: colors.success,
      borderRadius: vs(3),
    },
    missionsContainer: {
      marginBottom: vs(16),
    },
    missionsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: vs(12),
    },
    missionsScroll: {
      marginHorizontal: s(-16),
    },
    missionsScrollContent: {
      paddingHorizontal: s(16),
      paddingBottom: vs(10),
    },
    missionCard: {
      width: s(150),
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: ms(20),
      padding: s(16),
      marginRight: s(12),
    },
    missionDone: {
      borderColor: colors.successBorderAlpha,
    },
    missionProgressBase: {
      height: vs(2),
      backgroundColor: colors.border,
      width: '100%',
      marginVertical: vs(10),
    },
    missionProgressFill: {
      height: '100%',
      backgroundColor: colors.success,
    },
    startButton: {
      marginBottom: vs(24),
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginBottom: vs(16),
    },
    statCard: {
      width: '48%',
      backgroundColor: colors.card,
      borderRadius: ms(20),
      padding: s(16),
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: vs(12),
    },
    leaderboardSection: {
      backgroundColor: colors.modalBackground,
      borderRadius: ms(20),
      borderWidth: 1,
      borderColor: colors.borderTranslucent,
      marginBottom: vs(24),
      overflow: 'hidden',
    },
    leaderboardHeaderContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      padding: s(20),
      paddingBottom: vs(16),
    },
    leaderboardTitleContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    leaderboardTabs: {
      flexDirection: 'row',
      gap: s(8),
      alignItems: 'center',
      marginTop: vs(-10),
    },
    leaderboardTab: {
      paddingHorizontal: s(14),
      paddingVertical: vs(5),
      borderRadius: ms(20),
      borderWidth: 1.5,
      borderColor: colors.borderTranslucent,
      backgroundColor: colors.cardDark,
    },
    leaderboardTabActive: {
      borderColor: colors.successAlpha40,
      backgroundColor: colors.successAlpha,
    },
    leaderboardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: vs(12),
      paddingHorizontal: s(16),
      borderTopWidth: 1,
      borderTopColor: colors.borderTranslucent,
    },
    accountCard: {
      backgroundColor: colors.card,
      borderRadius: ms(24),
      padding: s(16),
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: vs(20),
    },
    accountHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: vs(10),
    },
    planPill: {
      backgroundColor: colors.infoAlpha,
      paddingHorizontal: s(12),
      paddingVertical: vs(4),
      borderRadius: ms(10),
    },
    accountRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: vs(10),
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    idleState: {
      flex: 1,
    },
    chargingState: {
      flex: 1,
    },
    liveCard: {
      borderRadius: ms(24),
      paddingHorizontal: s(16),
      paddingVertical: vs(10),
      borderWidth: 1.5,
      borderColor: colors.successAlpha40,
      marginBottom: vs(16),
      overflow: 'hidden',
    },
    liveHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: vs(24),
    },
    liveBadge: {
      backgroundColor: colors.successAlpha,
      paddingHorizontal: s(10),
      paddingVertical: vs(4),
      borderRadius: ms(20),
    },
    mainProgressContainer: {
      alignItems: 'flex-start',
      marginBottom: vs(24),
    },
    statusBarContainer: {
      width: '100%',
      height: vs(8),
      backgroundColor: colors.border,
      borderRadius: vs(4),
      marginBottom: vs(10),
    },
    statusBar: {
      height: '100%',
      backgroundColor: colors.success,
      borderRadius: vs(4),
    },
    statusScaleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: vs(24),
    },
    sessionBriefRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: vs(24),
      paddingHorizontal: s(10),
    },
    briefCol: {
      alignItems: 'center',
    },
    stopButton: {
      marginTop: vs(5),
    },
    missionsSection: {
      marginBottom: vs(24),
    },
    missionsColum: {
      flexDirection: 'row',
      gap: s(12),
      marginTop: vs(12),
    },
    missionProgressLine: {
      height: vs(2),
      width: '100%',
      marginVertical: vs(10),
    },
    accountSection: {
      backgroundColor: colors.card,
      borderRadius: ms(24),
      padding: s(16),
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: vs(40),
    },
    accountItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: vs(14),
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    skinsModalContainer: {
      flex: 1,
      backgroundColor: colors.modalBackdrop,
      justifyContent: 'flex-end',
    },
    skinsModalContent: {
      backgroundColor: colors.modalBackground,
      borderTopLeftRadius: ms(28),
      borderTopRightRadius: ms(28),
      padding: s(24),
      paddingBottom: vs(40),
      maxHeight: '75%',
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    smHandle: {
      width: s(36),
      height: vs(4),
      backgroundColor: colors.border,
      borderRadius: 2,
      alignSelf: 'center',
      marginBottom: vs(20),
    },
    skinsModalHeader: {
      marginBottom: vs(20),
    },
    skinsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      paddingBottom: vs(20),
    },
    skinOption: {
      width: (SCREEN_WIDTH - s(48) - s(12)) / 2,
      backgroundColor: colors.card,
      borderRadius: 14,
      padding: s(16),
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
      marginBottom: vs(12),
    },
    skinOptionActive: {
      borderColor: colors.success,
      backgroundColor: colors.primaryGlow,
    },
    skinOptionPremium: {
      borderColor: colors.warningBorderAlpha,
    },
    skinEmoji: {
      marginBottom: vs(8),
    },
    skinName: {
      marginBottom: vs(4),
      textAlign: 'center',
    },
    skinsModalButton: {
      marginTop: vs(16),
      height: vs(40),
      borderRadius: 12,
    },
  });

export default createStyles;
